#!usr/bin/python2
#coding=utf-8
# Created by Stéphane
# Le credit pour ce code va a Mr Steph
import requests,os,sys,time,datetime,random,calendar
from time import sleep   
from datetime import datetime  
 
os.system('clear')
print("\t\t\033[1;93m***\033[1;97m CALENDAR OF\033[1;96m 2020 \033[1;93m ***\033[1;92m")
for i in range(1,13,1):
    print(calendar.month(2020,i))
